# Generated by Django 3.1 on 2020-08-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rBlog', '0004_auto_20200819_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='null', max_length=200, verbose_name='Author'),
            preserve_default=False,
        ),
    ]
